Repository mdx-js/eslint-mdx, pull requests merged in 2022-06, with the labels that each got.

#401 fix: same markdown processor cached for .md and .mdx
  packages/eslint-mdx/src/worker.ts
Labels: 👶 semver/patch

#402 fix: incorrect default ecmaVersion (2022 is unavailable yet)
  packages/eslint-mdx/src/parser.ts
  yarn.lock
Labels: 🐛 type/bug, 👶 semver/patch

#405 fix: add missing unist-util-visit and vfile deps
  package.json
  packages/eslint-mdx/package.json
  packages/eslint-plugin-mdx/package.json
  yarn.lock
Labels: 🐛 type/bug, 📦 area/deps, 👶 semver/patch
