Repository mdx-js/eslint-mdx, pull requests merged in 2024-01, with the labels that each got.

#509 build: migrate to yarn v4
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/pkg-size.yml
  .github/workflows/release.yml
  .yarn/plugins/plugin-prepare-lifecycle.cjs
  .yarnrc.yml
  package.json
  packages/eslint-mdx/package.json
  packages/eslint-mdx/src/meta.ts
  packages/eslint-mdx/src/worker.ts
  packages/eslint-plugin-mdx/src/configs/recommended.ts
  packages/eslint-plugin-mdx/src/meta.ts
  patches/eslint+8.56.0.patch
  patches/string-length+4.0.2.patch
  test/__snapshots__/fixtures.test.ts.snap
  test/fixtures.test.ts
  test/parser.test.ts
  tsconfig.json
  yarn.lock
Labels: 📦 area/deps, 🏡 area/internal

#510 chore: migrate to concurrently for Windows compatibility
  package.json
  yarn.lock
Labels: 📦 area/deps, 🏡 area/internal

#511 chore: log error details on `--debug` flag enabled
  .changeset/poor-lions-buy.md
  packages/eslint-mdx/src/parser.ts
Labels: 👶 semver/patch

#514 chore: bump synckit
  .changeset/light-horses-tap.md
  .github/workflows/release.yml
  package.json
  packages/eslint-mdx/package.json
  yarn.lock
Labels: 📦 area/deps

#521 fix: undefined place in vFile message causes TypeError
  .changeset/new-brooms-visit.md
  packages/eslint-plugin-mdx/src/rules/remark.ts
Labels: 🐛 type/bug, 👶 semver/patch
